#!/usr/bin/env bash
# List all non executable python files in this project

cd ..
function list_non_executable()
{
	if [ ! -x $1 ] # Is it executable?
	then
		ls -n "$1" | tr -s " " " " | cut -d " " -f1,6-
	fi
}

files=()
while IFS= read -r -d "" fil
do
 files+=("$fil")
done < <(find . -type f -name "*.py" -print0)


# List all non executable file in the list
for f in ${files[@]}
do list_non_executable "$f"
# ls -n "$f" | tr -s " " " " | cut -d " " -f1,6-
done
